### ISSUE TITLE
Xətalar

### ISSUE THREAD

**Issue by ismayil** [CodeAcademyP502/14-01-2018-AytajGasimova095#1]
Aytac bu nə dilində yazır? )))
Balans bəzən mənfiyə gedir, ümumi balansı yoxlamadan zəng etməyə icazə verirsən, daxil olanın rəqəm və ya hərf olmasını yoxlamırsan
**Nəticə 85**

**Comment by AytajGasimova095** [comment]
maraqlı olsun deyə çin dilinde yazmışam
